/*
 * This file is part of RFrEAK. For licensing and copyright information
 * please see the file COPYING in the root directory of this
 * distribution or contact <robin.nunkesser@udo.edu>.
 * 
 * This file is a modification of the original file distributed with
 * FrEAK (http://sourceforge.net/projects/freak427/).
 * Last modification: 07/11/2007
 */

package freak.gui.runframe;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 * Autogenerated Menu.
 * @author  Stefan
 */
public class RunFrameUI extends AbstractRunFrame {
	protected FreakDesktopPane desktop;
	protected ReplayPanel blinkingR;
	
	public void viewFilenameInTitle(String s)
	{
		setTitle("RFrEAK "+s);
	}
	
	public RunFrameUI() {
		initComponents();
		changeDesktop();
		addAccelerators();
		if (UIManager.getLookAndFeel().getID().equals("Aqua")) {
			aquaLayoutAdaptions();
		} else if (UIManager.getLookAndFeel().getID().equals("Metal"))  {
			metalLayoutAdaptions();
		}
		pack();
	}
	
	private void changeDesktop() {
		desktop = new FreakDesktopPane();
		blinkingR = new ReplayPanel();
		ROverlayPane rPane = new ROverlayPane(desktop.getDelegate(), blinkingR);
				
		desktopPanel.removeAll();
		desktopPanel.add(rPane);
	}
	
	private void addAccelerators() {
		int modifier =  Toolkit.getDefaultToolkit().getMenuShortcutKeyMask();
		jMenuItemNew.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N, modifier));
		jMenuItemOpen.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_O, modifier));
		jMenuItemSave.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, modifier));
		jMenuItemExit.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_Q, modifier));
		jMenuItemEdit.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_E, modifier));
		jMenuItemHelp.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0));
	}
	
	private void aquaLayoutAdaptions() {
	    jButtonSkipToStart.setMargin(new Insets(11, 25, 8, 22));
        jButtonSkipBack.setMargin(new Insets(11, 25, 8, 22));
        jButtonSuspend.setMargin(new Insets(11, 25, 8, 22));
		jButtonStart.setMargin(new Insets(11, 25, 8, 22));
        jButtonSkipForward.setMargin(new Insets(11, 25, 8, 22));
        jButtonSkipToEnd.setMargin(new Insets(11, 25, 8, 22));
		
		GridBagLayout cpLayout = (GridBagLayout)controlPanel.getLayout();
		GridBagConstraints constraints = cpLayout.getConstraints(jSliderGeneration);
		constraints.insets.bottom = 0;
		cpLayout.setConstraints(jSliderGeneration, constraints);
		
		((GridLayout)buttonPanel.getLayout()).setHgap(0);
		
		controlPanel.setBorder(new EmptyBorder(4, 9, 12, 9));
		constraints = cpLayout.getConstraints(buttonPanel);
		constraints.insets.left = 5;
		cpLayout.setConstraints(buttonPanel, constraints);
		
		infoPanel.setBorder(new EmptyBorder(12, 14, 12, 12));
		
		jButtonStart.setText("");
   	}
	
	private void metalLayoutAdaptions() {
		controlPanel.setBorder(new EmptyBorder(12, 6, 12, 6));
		GridBagLayout cpLayout = (GridBagLayout)controlPanel.getLayout();
		GridBagConstraints constraints = cpLayout.getConstraints(buttonPanel);
		constraints.insets.left = 6;
		cpLayout.setConstraints(buttonPanel, constraints);
   	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        GridBagConstraints gridBagConstraints;

        rootPanel = new JPanel();
        infoPanel = new JPanel();
        jLabelSearchSpace = new JLabel();
        jLabelFitnessFunction = new JLabel();
        jLabelRun = new JLabel();
        jLabelGeneration = new JLabel();
        jSpinnerRun = new JSpinner();
        jSpinnerGeneration = new JSpinner();
        jLabelBatch = new JLabel();
        jSpinnerBatch = new JSpinner();
        spacer1 = new JPanel();
        jButtonQuickStart = new JButton();
        controlPanel = new JPanel();
        jSliderSpeed = new JSlider();
        jLabelSpeed = new JLabel();
        speedLimitCheckBox = new JCheckBox();
        jSliderGeneration = new JSlider();
        buttonPanel = new JPanel();
        jButtonSkipToStart = new JButton();
        jButtonSkipBack = new JButton();
        jButtonSuspend = new JButton();
        jButtonStart = new JButton();
        jButtonSkipForward = new JButton();
        jButtonSkipToEnd = new JButton();
        spacer2 = new JPanel();
        jTextFieldSpeed = new JTextField();
        spacer3 = new JPanel();
        desktopPanel = new JPanel();
        jDesktopPane1 = new JDesktopPane();
        jSeparator3 = new JSeparator();
        jSeparator4 = new JSeparator();
        jMenuBar1 = new JMenuBar();
        jMenuFile = new JMenu();
        jMenuItemNew = new JMenuItem();
        jMenuItemOpen = new JMenuItem();
        jMenuItemSave = new JMenuItem();
        jMenuItemSaveAs = new JMenuItem();
        jSeparator1 = new JSeparator();
        jMenuItemExit = new JMenuItem();
        jMenuEdit = new JMenu();
        jMenuItemEdit = new JMenuItem();
        jMenuItemConfigureView = new JMenuItem();
        jMenuControl = new JMenu();
        jMenuItemStart = new JMenuItem();
        jMenuItemSuspend = new JMenuItem();
        jSeparator5 = new JSeparator();
        jMenuItemSkipBack = new JMenuItem();
        jMenuItemSkipForward = new JMenuItem();
        jMenuItemSkipToStart = new JMenuItem();
        jMenuItemSkipToEnd = new JMenuItem();
        jSeparator6 = new JSeparator();
        jMenuItemGoTo = new JMenuItem();
        jMenuViews = new JMenu();
        jMenuItemTile = new JMenuItem();
        jMenuItemCascade = new JMenuItem();
        jMenuItemMinimize = new JMenuItem();
        jMenuItemRestore = new JMenuItem();
        jMenuItemClose = new JMenuItem();
        jMenuHelp = new JMenu();
        jMenuItemHelp = new JMenuItem();
        jSeparator2 = new JSeparator();
        jMenuItemAbout = new JMenuItem();

        setTitle("RFrEAK");
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                exitForm(evt);
            }
        });

        rootPanel.setLayout(new GridBagLayout());

        infoPanel.setLayout(new GridBagLayout());

        infoPanel.setBorder(new EmptyBorder(new Insets(12, 12, 12, 12)));
        jLabelSearchSpace.setFont(new Font("Dialog", 1, 18));
        jLabelSearchSpace.setText("Search Space");
        jLabelSearchSpace.setToolTipText("The search space of the current schedule");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        infoPanel.add(jLabelSearchSpace, gridBagConstraints);

        jLabelFitnessFunction.setText("Fitness Function");
        jLabelFitnessFunction.setToolTipText("The fitness function of the current schedule");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(6, 0, 0, 0);
        infoPanel.add(jLabelFitnessFunction, gridBagConstraints);

        jLabelRun.setText("Run:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(11, 0, 0, 0);
        infoPanel.add(jLabelRun, gridBagConstraints);

        jLabelGeneration.setText("Generation:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(11, 0, 0, 0);
        infoPanel.add(jLabelGeneration, gridBagConstraints);

        jSpinnerRun.setToolTipText("Jump to a different run  in the current batch");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(6, 0, 0, 0);
        infoPanel.add(jSpinnerRun, gridBagConstraints);

        jSpinnerGeneration.setToolTipText("Jump to a different generation in the current run");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(6, 0, 0, 0);
        infoPanel.add(jSpinnerGeneration, gridBagConstraints);

        jLabelBatch.setText("Batch:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(24, 0, 0, 0);
        infoPanel.add(jLabelBatch, gridBagConstraints);

        jSpinnerBatch.setToolTipText("Jump to a different batch");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(6, 0, 0, 0);
        infoPanel.add(jSpinnerBatch, gridBagConstraints);

        spacer1.setLayout(new BorderLayout());

        spacer1.setMinimumSize(new Dimension(120, 6));
        spacer1.setPreferredSize(new Dimension(120, 200));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        infoPanel.add(spacer1, gridBagConstraints);

        jButtonQuickStart.setText("Quick Start GPAS");
        jButtonQuickStart.setToolTipText("Get a simplified dialog to start GPAS");
        jButtonQuickStart.setHorizontalTextPosition(SwingConstants.RIGHT);
        jButtonQuickStart.setMargin(null);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(6, 0, 0, 0);
        infoPanel.add(jButtonQuickStart,gridBagConstraints);
        
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        rootPanel.add(infoPanel, gridBagConstraints);

        controlPanel.setLayout(new GridBagLayout());

        controlPanel.setBorder(new EmptyBorder(new Insets(6, 12, 12, 12)));
        jSliderSpeed.setMaximum(500);
        jSliderSpeed.setMinimum(-100);
        jSliderSpeed.setToolTipText("Speed limit");
        jSliderSpeed.setValue(100);
        jSliderSpeed.setMinimumSize(null);
        jSliderSpeed.setPreferredSize(null);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        controlPanel.add(jSliderSpeed, gridBagConstraints);

        jLabelSpeed.setText("Speed Limit:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new Insets(0, 12, 0, 6);
        controlPanel.add(jLabelSpeed, gridBagConstraints);

        speedLimitCheckBox.setSelected(true);
        speedLimitCheckBox.setToolTipText("Enable or disable speed limit");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new Insets(0, 0, 0, 6);
        controlPanel.add(speedLimitCheckBox, gridBagConstraints);

        jSliderGeneration.setMajorTickSpacing(20);
        jSliderGeneration.setMinorTickSpacing(1);
        jSliderGeneration.setPaintLabels(true);
        jSliderGeneration.setPaintTicks(true);
        jSliderGeneration.setMinimumSize(null);
        jSliderGeneration.setPreferredSize(null);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(0, 0, 6, 0);
        controlPanel.add(jSliderGeneration, gridBagConstraints);

        buttonPanel.setLayout(new GridLayout(1, 0));

        jButtonSkipToStart.setIcon(new ImageIcon(getClass().getResource("/freak/gui/runframe/StepBackFar.gif")));
        jButtonSkipToStart.setToolTipText("Go back to the start of the simulation");
        jButtonSkipToStart.setMargin(null);
        buttonPanel.add(jButtonSkipToStart);

        jButtonSkipBack.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/media/StepBack16.gif")));
        jButtonSkipBack.setToolTipText("Step back to the last start of a run");
        jButtonSkipBack.setMargin(null);
        buttonPanel.add(jButtonSkipBack);

        jButtonSuspend.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/media/Pause16.gif")));
        jButtonSuspend.setToolTipText("Suspend");
        buttonPanel.add(jButtonSuspend);

        jButtonStart.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/media/Play16.gif")));
        jButtonStart.setToolTipText("Start");
        jButtonStart.setHorizontalTextPosition(SwingConstants.RIGHT);
        jButtonStart.setMargin(null);
        buttonPanel.add(jButtonStart);

        jButtonSkipForward.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/media/StepForward16.gif")));
        jButtonSkipForward.setToolTipText("Jump to the start of the next run");
        jButtonSkipForward.setMargin(null);
        buttonPanel.add(jButtonSkipForward);

        jButtonSkipToEnd.setIcon(new ImageIcon(getClass().getResource("/freak/gui/runframe/StepForwardFar.gif")));
        jButtonSkipToEnd.setToolTipText("Jump forward to the last known generation");
        jButtonSkipToEnd.setMargin(null);
        buttonPanel.add(jButtonSkipToEnd);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        controlPanel.add(buttonPanel, gridBagConstraints);

        spacer2.setLayout(new BorderLayout());

        spacer2.setMinimumSize(new Dimension(100, 0));
        spacer2.setPreferredSize(new Dimension(300, 0));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        controlPanel.add(spacer2, gridBagConstraints);

        jTextFieldSpeed.setHorizontalAlignment(JTextField.TRAILING);
        jTextFieldSpeed.setText("10.00");
        jTextFieldSpeed.setToolTipText("Speed limit in generations per second");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(0, 0, 0, 6);
        controlPanel.add(jTextFieldSpeed, gridBagConstraints);

        spacer3.setLayout(new BorderLayout());

        spacer3.setMinimumSize(new Dimension(80, 0));
        spacer3.setPreferredSize(new Dimension(80, 0));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(0, 0, 0, 6);
        controlPanel.add(spacer3, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        rootPanel.add(controlPanel, gridBagConstraints);

        desktopPanel.setLayout(new BorderLayout());

        desktopPanel.add(jDesktopPane1, BorderLayout.CENTER);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        rootPanel.add(desktopPanel, gridBagConstraints);

        jSeparator3.setMinimumSize(new Dimension(0, 2));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        rootPanel.add(jSeparator3, gridBagConstraints);

        jSeparator4.setOrientation(SwingConstants.VERTICAL);
        jSeparator4.setMinimumSize(new Dimension(2, 0));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        rootPanel.add(jSeparator4, gridBagConstraints);

        getContentPane().add(rootPanel, BorderLayout.CENTER);

        jMenuFile.setMnemonic('F');
        jMenuFile.setText("File");
        jMenuItemNew.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/New16.gif")));
        jMenuItemNew.setMnemonic('N');
        jMenuItemNew.setText("New...");
        jMenuItemNew.setToolTipText("Create a new schedule");
        jMenuFile.add(jMenuItemNew);

        jMenuItemOpen.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Open16.gif")));
        jMenuItemOpen.setMnemonic('O');
        jMenuItemOpen.setText("Open...");
        jMenuItemOpen.setToolTipText("Load a schedule");
        jMenuFile.add(jMenuItemOpen);

        jMenuItemSave.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Save16.gif")));
        jMenuItemSave.setMnemonic('S');
        jMenuItemSave.setText("Save");
        jMenuItemSave.setToolTipText("Save the current schedule");
        jMenuFile.add(jMenuItemSave);

        jMenuItemSaveAs.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/SaveAs16.gif")));
        jMenuItemSaveAs.setMnemonic('A');
        jMenuItemSaveAs.setText("Save As...");
        jMenuItemSaveAs.setToolTipText("Save the current schedule to a different location");
        jMenuFile.add(jMenuItemSaveAs);

        jMenuFile.addSeparator();

        jMenuItemExit.setMnemonic('X');
        jMenuItemExit.setText("Exit");
        jMenuItemExit.setToolTipText("Terminate FrEAK");
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setMnemonic('E');
        jMenuEdit.setText("Edit");
        jMenuItemEdit.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Edit16.gif")));
        jMenuItemEdit.setMnemonic('E');
        jMenuItemEdit.setText("Edit Schedule...");
        jMenuItemEdit.setToolTipText("Modify the configuration of the current schedule");
        jMenuEdit.add(jMenuItemEdit);

        jMenuItemConfigureView.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Preferences16.gif")));
        jMenuItemConfigureView.setMnemonic('C');
        jMenuItemConfigureView.setText("Configure Selected View");
        jMenuItemConfigureView.setToolTipText("Modify the configuration of the selected view");
        jMenuEdit.add(jMenuItemConfigureView);

        jMenuBar1.add(jMenuEdit);

        jMenuControl.setMnemonic('C');
        jMenuControl.setText("Control");
        jMenuItemStart.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/media/Play16.gif")));
        jMenuItemStart.setMnemonic('S');
        jMenuItemStart.setText("Start");
        jMenuItemStart.setToolTipText("Start or continue the current Schedule");
        jMenuControl.add(jMenuItemStart);

        jMenuItemSuspend.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/media/Pause16.gif")));
        jMenuItemSuspend.setMnemonic('P');
        jMenuItemSuspend.setText("Suspend");
        jMenuItemSuspend.setToolTipText("Pause the current Schedule");
        jMenuControl.add(jMenuItemSuspend);

        jMenuControl.addSeparator();

        jMenuItemSkipBack.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/media/StepBack16.gif")));
        jMenuItemSkipBack.setText("Step Back");
        jMenuItemSkipBack.setToolTipText("Step back to the last start of a run");
        jMenuControl.add(jMenuItemSkipBack);

        jMenuItemSkipForward.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/media/StepForward16.gif")));
        jMenuItemSkipForward.setText("Skip Run");
        jMenuItemSkipForward.setToolTipText("Jump to the start of the next run");
        jMenuControl.add(jMenuItemSkipForward);

        jMenuItemSkipToStart.setIcon(new ImageIcon(getClass().getResource("/freak/gui/runframe/StepBackFar.gif")));
        jMenuItemSkipToStart.setText("Go to Start");
        jMenuItemSkipToStart.setToolTipText("Go back to the start of the simulation");
        jMenuControl.add(jMenuItemSkipToStart);

        jMenuItemSkipToEnd.setIcon(new ImageIcon(getClass().getResource("/freak/gui/runframe/StepForwardFar.gif")));
        jMenuItemSkipToEnd.setText("Go to End");
        jMenuItemSkipToEnd.setToolTipText("Jump forward to the last known generation");
        jMenuControl.add(jMenuItemSkipToEnd);

        jMenuControl.addSeparator();

        jMenuItemGoTo.setMnemonic('G');
        jMenuItemGoTo.setText("Go to...");
        jMenuItemGoTo.setToolTipText("Jump to a specified generation");
        jMenuControl.add(jMenuItemGoTo);

        jMenuBar1.add(jMenuControl);

        jMenuViews.setMnemonic('V');
        jMenuViews.setText("Views");
        jMenuItemTile.setMnemonic('T');
        jMenuItemTile.setText("Tile");
        jMenuViews.add(jMenuItemTile);

        jMenuItemCascade.setMnemonic('C');
        jMenuItemCascade.setText("Cascade");
        jMenuViews.add(jMenuItemCascade);

        jMenuItemMinimize.setMnemonic('M');
        jMenuItemMinimize.setText("Minimize All");
        jMenuViews.add(jMenuItemMinimize);

        jMenuItemRestore.setMnemonic('R');
        jMenuItemRestore.setText("Restore All");
        jMenuViews.add(jMenuItemRestore);

        jMenuItemClose.setMnemonic('C');
        jMenuItemClose.setText("Close All");
        jMenuViews.add(jMenuItemClose);

        jMenuBar1.add(jMenuViews);

        jMenuHelp.setMnemonic('H');
        jMenuHelp.setText("Help");
        jMenuItemHelp.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Help16.gif")));
        jMenuItemHelp.setMnemonic('H');
        jMenuItemHelp.setText("Help");
        jMenuItemHelp.setToolTipText("Show the reference manual");
        jMenuHelp.add(jMenuItemHelp);

        jMenuHelp.addSeparator();

        jMenuItemAbout.setIcon(new ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/About16.gif")));
        jMenuItemAbout.setMnemonic('A');
        jMenuItemAbout.setText("About");
        jMenuItemAbout.setToolTipText("Show version and license information");
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

	/** Exit the Application */
	private void exitForm(WindowEvent evt) { //GEN-FIRST:event_exitForm
		System.exit(0);
	} //GEN-LAST:event_exitForm

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) throws Exception {
		//System.out.println(Arrays.asList(UIManager.getInstalledLookAndFeels()));
		//UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
		//UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
		RunFrameUI f = new RunFrameUI();
		
		f.setLocationRelativeTo(null);
		f.setVisible(true);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected JPanel buttonPanel;
    protected JPanel controlPanel;
    protected JPanel desktopPanel;
    protected JPanel infoPanel;
    protected JButton jButtonQuickStart;
    protected JButton jButtonSkipBack;
    protected JButton jButtonSkipForward;
    protected JButton jButtonSkipToEnd;
    protected JButton jButtonSkipToStart;
    protected JButton jButtonStart;
    protected JButton jButtonSuspend;
    protected JDesktopPane jDesktopPane1;
    protected JLabel jLabelBatch;
    protected JLabel jLabelFitnessFunction;
    protected JLabel jLabelGeneration;
    protected JLabel jLabelRun;
    protected JLabel jLabelSearchSpace;
    protected JLabel jLabelSpeed;
    protected JMenuBar jMenuBar1;
    protected JMenu jMenuControl;
    protected JMenu jMenuEdit;
    protected JMenu jMenuFile;
    protected JMenu jMenuHelp;
    protected JMenuItem jMenuItemAbout;
    protected JMenuItem jMenuItemCascade;
    protected JMenuItem jMenuItemClose;
    protected JMenuItem jMenuItemConfigureView;
    protected JMenuItem jMenuItemEdit;
    protected JMenuItem jMenuItemExit;
    protected JMenuItem jMenuItemGoTo;
    protected JMenuItem jMenuItemHelp;
    protected JMenuItem jMenuItemMinimize;
    protected JMenuItem jMenuItemNew;
    protected JMenuItem jMenuItemOpen;
    protected JMenuItem jMenuItemRestore;
    protected JMenuItem jMenuItemSave;
    protected JMenuItem jMenuItemSaveAs;
    protected JMenuItem jMenuItemSkipBack;
    protected JMenuItem jMenuItemSkipForward;
    protected JMenuItem jMenuItemSkipToEnd;
    protected JMenuItem jMenuItemSkipToStart;
    protected JMenuItem jMenuItemStart;
    protected JMenuItem jMenuItemSuspend;
    protected JMenuItem jMenuItemTile;
    protected JMenu jMenuViews;
    protected JSeparator jSeparator1;
    protected JSeparator jSeparator2;
    protected JSeparator jSeparator3;
    protected JSeparator jSeparator4;
    protected JSeparator jSeparator5;
    protected JSeparator jSeparator6;
    protected JSlider jSliderGeneration;
    protected JSlider jSliderSpeed;
    protected JSpinner jSpinnerBatch;
    protected JSpinner jSpinnerGeneration;
    protected JSpinner jSpinnerRun;
    protected JTextField jTextFieldSpeed;
    protected JPanel rootPanel;
    protected JPanel spacer1;
    protected JPanel spacer2;
    private JPanel spacer3;
    protected JCheckBox speedLimitCheckBox;
    // End of variables declaration//GEN-END:variables

}
